# Generated by Django 5.2.16 on 2026-07-13 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPageConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='CarX', max_length=50)),
                ('hero_title', models.CharField(default='Find,Book and Rent a Car in Easy Steps', max_length=150)),
                ('hero_subtitle', models.CharField(default='Get access to a diverse fleet of high-quality vehicles with flexible booking plans.')),
                ('hero_cta_text', models.CharField(default='Explore Cars', max_length=50)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='cms/hero/')),
                ('contact_email', models.CharField(default='support@carx.com')),
                ('contact_phone', models.CharField(default='+250 784 445 193', max_length=15)),
                ('copyright_text', models.CharField(default=' 2026 CarX. All right reserved.', max_length=150)),
            ],
            options={
                'verbose_name': 'Landing page Configuration',
                'verbose_name_plural': 'Landing Page Configuration',
            },
        ),
        migrations.CreateModel(
            name='NavbarLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text="The display text for the link (e.g., 'Cars')", max_length=50)),
                ('url_path', models.CharField(help_text="The react router route path (e.g., '/cars')", max_length=100)),
                ('icon_name', models.CharField(blank=True, help_text="React icon class or string identifier (e.g., 'CarIcon')", max_length=50, null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Sorting order in the navbar')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
