# Generated by Django 5.2.16 on 2026-07-14 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpageconfig',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
