# Generated by Django 5.2.16 on 2026-07-14 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_landingpageconfig_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_email', models.EmailField(default='support@carx.com', max_length=254)),
                ('contact_phone', models.CharField(default='+250 784 445 193', max_length=20)),
                ('address', models.TextField(blank=True, default='Kigali, Rwanda')),
                ('about_us_short', models.TextField(blank=True, help_text='A brief snippet about your company')),
            ],
            options={
                'verbose_name': 'Company Information',
                'verbose_name_plural': 'Company Information',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='cms/features/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FooterConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copyright_text', models.CharField(default='© 2026 CarX. All rights reserved.', max_length=150)),
                ('footer_bottom_text', models.CharField(blank=True, help_text='Any additional small print or links.', max_length=250)),
            ],
            options={
                'verbose_name': 'Footer Configuration',
                'verbose_name_plural': 'Footer Configuration',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon_name', models.CharField(blank=True, help_text="CSS class or Lucide/FontAwesome icon name (e.g., 'car', 'calendar')", max_length=50)),
                ('order', models.PositiveIntegerField(default=0, help_text='Controls the display order on the landing page.')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'Twitter / X'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('youtube', 'YouTube')], max_length=50)),
                ('url', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('client_role', models.CharField(blank=True, help_text='e.g. CEO, Customer, Traveler', max_length=100)),
                ('client_avatar', models.ImageField(blank=True, null=True, upload_to='cms/testimonials/')),
                ('review_text', models.TextField()),
                ('rating', models.PositiveIntegerField(default=5, help_text='Star rating from 1 to 5')),
            ],
        ),
        migrations.AlterModelOptions(
            name='landingpageconfig',
            options={'verbose_name': 'Landing page Hero Configuration', 'verbose_name_plural': 'Landing Page Hero Configuration'},
        ),
    ]
