# Generated by Django 5.2.16 on 2026-07-22 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_companyinformation_faq_feature_footerconfig_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingpageconfig',
            name='contact_phone',
            field=models.CharField(default='0 784 445 193', max_length=25),
        ),
    ]
