# Generated by Django 5.2.16 on 2026-07-23 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_alter_sociallink_options_alter_testimonial_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navbarlink',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
