# Generated by Django 5.2.16 on 2026-07-23 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_alter_navbarlink_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingpageconfig',
            name='contact_email',
            field=models.CharField(default='support@carx.com', max_length=100),
        ),
        migrations.AlterField(
            model_name='landingpageconfig',
            name='hero_subtitle',
            field=models.CharField(default='Get access to a diverse fleet of high-quality vehicles with flexible booking plans.', max_length=255),
        ),
    ]
